USE [UNI]
GO

CREATE TABLE [dbo].[ALUMNO](
	[DNI] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[APELLIDO] [varchar](50) NOT NULL,
	[EMAIL] [varchar](255),
 CONSTRAINT [PK_ALUMNO] PRIMARY KEY CLUSTERED 
(
	[DNI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[MATERIA](
	[ID] [int] NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
	[ANIO] INT NOT NULL,
 CONSTRAINT [PK_MATERIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[FINALES](
	[ID] [int] NOT NULL,
	[DNI] [int] NOT NULL,
	[ID_MATERIA] [int] NOT NULL,
	[NOTA] [numeric](4, 2) NOT NULL,
	[FECHA_FINAL] [DATE] NOT NULL,
 CONSTRAINT [PK_FINALES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


GO

ALTER TABLE [dbo].[FINALES]  WITH CHECK ADD  CONSTRAINT [FK_FINALES_ALUMNO] FOREIGN KEY([DNI])
REFERENCES [dbo].[ALUMNO] ([DNI])
GO

ALTER TABLE [dbo].[FINALES] CHECK CONSTRAINT [FK_FINALES_ALUMNO]
GO

ALTER TABLE [dbo].[FINALES]  WITH CHECK ADD  CONSTRAINT [FK_FINALES_MATERIA] FOREIGN KEY([ID_MATERIA])
REFERENCES [dbo].[MATERIA] ([ID])
GO

ALTER TABLE [dbo].[FINALES] CHECK CONSTRAINT [FK_FINALES_MATERIA]
GO

